[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.scheduled]]
cron = "0 */4 * * 1-5"
command = "python monday_email_sender.py"