[
build
]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[
deploy
]
startCommand = "python monday_email_sender.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[
deploy.scheduled
]]
cron = "0 */4 * * 1-5"

[
nixpacks
]
start-command = "python monday_email_sender.py"