[deploy]
builder = "Docker"
start = "python3 /app/monday_email_sender.py"

[cron]
cronSchedule = "*/15 * * * *"
command = "python3 /app/monday_email_sender.py"

[build]
dockerfile = "./Dockerfile"

[env]
RAILWAY_CRON = "true"
